# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation

about:
    path: /about
    # the controller value has the format 'controller_class::method_name'
    controller: App\Controller\AboutController::index